import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

//import lib bootstrap vao layout tong cuc
import "bootstrap/dist/css/bootstrap.min.css";
//import BootstrapClient su dung bootstrap.bundle.min.js
import BootstrapClient from "@/components/BootstrapClient";
import "bootstrap-icons/font/bootstrap-icons.css";

//import global.css
import "./globals.css";

//import fontAwesome vaof nextjs
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

//import modal context va ToastContext dung cho global toan du an
import { ModalProvider } from "@/contexts/ModalContext";
import ToastProvider from "@/contexts/ToastContext";
import BackToTop from "@/components/client/BackToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        <ToastProvider>
          <ModalProvider>{children}</ModalProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
