spring.application.name=webapp

## bổ sung mysqldialect de ho tro viet cau truy van jpql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# them cau hinh de hibernate tutao/cup nhat cac bang dua tren entity cua ban
spring.jpa.hibernate.ddl-auto=update

## cau hinh port chay chinh cau spring boot localhost:8080
server.port=8080
## cho phep cau hinh localhot port 3000 cua nextjs dc chay song song voi port 8080 tren cung browser
client.url=http://localhost:3000

## 1 - tien hanh cau hinh mysql vao du an
spring.datasource.url= jdbc:mysql://localhost:3306/webapp_camera24h
spring.datasource.username = root
spring.datasource.password = lol123456
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

## cau hinh upload file -> luu tru img(img co ruot anh)
file.upload-dir=uploads

## cau hinh public url dan thu muc tinh(static location)
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/uploads/**

## gioi han kich co img khi upload
spring.servlet.multipart.max-file-size = 5MB
spring.servlet.multipart.max-request-size = 5MB




######cau hinh email de xac thuc khi dang kY tai khoan#######
##smtp.gmail.com laf ten mien host cua goole quy dinh, port 587(lts)
spring.mail.host=smtp.gmail.com
## port chay ten mien host  
spring.mail.port=587
#ten email dang ky
spring.mail.username=kingofgirls98@gmail.com
##password mat khau ung dung(mkung dung khong phai mk dang nhap gmail binh thuong)
spring.mail.password=lnrdkpnmoluezivg
##y nghia doan nay la coi co xac thuc khi dang nhap email khong
spring.mail.properties.mail.smtp.auth=true
##do minh su dung port host cua google 587 nen phai bat lts len de giup bao mat tot hon
spring.mail.properties.mail.smtp.starttls.enable=true
##bo sung them 2 dong giup tranh loi EOF(end of file) khi gui mail(dola loi nay do khong bat duoc bao mat no bi ngat ket noi giua chung)
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties..mail.smtp.ssl.trust=smtp.gmail.com